.Dd February 17, 2021
.Dt BUILTIN 1
.Os
.Sh NAME
.Nm cd ,
.Nm echo ,
.Nm env,
.Nm exit ,
.Nm setenv ,
.Nm unsetenv ,
.Nd shell built-in commands
.Sh DESCRIPTION
Shell builtin commands are commands that can be executed within the
running shell's process.
.Sh SEE ALSO
.Xr echo 1 ,
.Xr minishell 1
.Sh AUTHORS
This manual page was written by
.An Andrew Slyusar Aq a97k572@gmail.com .
