.Dd February 17, 2021
.Dt ECHO 1
.Os
.Sh NAME
.Nm echo
.Nd write arguments to the standard output
.Sh SYNOPSIS
.Nm
.Op Fl n
.Op Ar string ...
.Sh DESCRIPTION
The
.Nm
utility writes any specified operands, separated by single blank
.Pq Ql "\ "
characters and followed by a newline
.Pq Ql \en
character, to the standard output.
.Pp
The following option is available:
.Bl -tag -width flag
.It Fl n
Do not print the trailing newline character.
.El
.Pp
Some shells may provide a builtin
.Nm
command which is similar or identical to this utility.
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr builtin 1 ,
.Xr minishell 1
.Sh STANDARDS
The
.Nm
utility conforms to
.St -p1003.1-2001 .
