.TH ECHO 1 "February 08, 2021" "FT" "FT General Commands Manual"
.SH NAME
.B echo
\-\- write arguments to the standard output
.SH SYNOPSIS
.B echo
[\fIstring ...\fR]
.SH DESCRIPTION
The
.B echo
utility writes its arguments to standard output, followed by a <newline>.
If there are no arguments, only the <newline> is written.
.SH EXIT STATUS
The
.B echo
utility exits 0 on success.
.SH SEE ALSO
builtin(1), minishell(1)
.SH STANDARDS
The
.B echo
utility conforms to IEEE Std 1003.1-2017 (``POSIX.1'').
