.TH EXIT 1 "February 08, 2021" "FT" "FT General Commands Manual"
.SH NAME
.B exit
\-\- cause the shell to exit
.SH SYNOPSIS
.B exit
[ \fIn\fR ]
.SH DESCRIPTION
The
.B exit
utility writes its arguments to standard output, followed by a <newline>.
If there are no arguments, only the <newline> is written.
.SH EXIT STATUS
The
.B exit
utility exits 0 on success.
.SH SEE ALSO
builtin(1), minishell(1)
