name: "PVS-Studio"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        wget -q -O - https://files.viva64.com/etc/pubkey.txt | sudo apt-key add -
        sudo wget -O /etc/apt/sources.list.d/viva64.list https://files.viva64.com/etc/viva64.list
        sudo apt-get update && sudo apt-get install pvs-studio
    - name: License
      env:
        MAIL: ${{ secrets.PVS_MAIL }}
        KEY: ${{ secrets.PVS_KEY }}
      run: pvs-studio-analyzer credentials $MAIL $KEY
    - name: Build
      run: pvs-studio-analyzer trace -- make
    - name: Analyze
      run: |
        pvs-studio-analyzer analyze -r ./ -l ~/.config/PVS-Studio/PVS-Studio.lic -e libft
        plog-converter -a GA:1,2 -t sarif -o results.sarif PVS-Studio.log
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif
