name: ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo gem install bundler
        git clone https://github.com/42Paris/norminette.git ~/norminette
        cd ~/norminette && bundle
    - name: Norminette
      run: ~/norminette/norminette.rb .
    - name: Build
      run: make
